name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push for Main Branch (latest)
      - name: Build and Push Docker Image (latest)
        if: github.ref_name == 'main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/heif-convert:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/heif-convert:latest

      # Build and Push for Tags (versioned)
      - name: Build and Push Docker Image (tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/heif-convert:${{ github.ref_name }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/heif-convert:${{ github.ref_name }}
