name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on commits to the main branch
    tags:
      - 'v*' # Trigger on Git tags that start with "v"
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Step 3: Build and Push for Main Branch (latest)
      - name: Build and Push Docker Image (latest)
        if: github.ref_name == 'main'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/heif-convert:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/heif-convert:latest

      # Step 4: Build and Push for Tags (versioned)
      - name: Build and Push Docker Image (tagged)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${{ github.ref_name }}
          echo "Building and pushing image with tag: $TAG"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/heif-convert:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/heif-convert:$TAG
